name: Upload SQL to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload SQL files to Azure Synapse
        run: |
          for file in sqlfiles/*.sql; do
            az synapse sql pool sql-uploaded-script create --workspace-name satya-synapse-demo --sql-pool-name "Built-in" --database-name "RAMS-demo" --name "$(basename "$file")" --definition-file "$file"
          done

