name: Upload SQL to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/setup-azure-powershell@v1
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload SQL files to Azure Synapse
        run: |
         $localFolderPath = "\sqlfiles"
         $workspaceName = "satya-synapse-demo"
         $sqlPoolName = "Built-in"
         $databaseName = "RAMS-demo"
         $scriptFiles = Get-ChildItem -Path $localFolderPath -Filter *.sql -File

         foreach ($scriptFile in $scriptFiles) {
          $scriptFilePath = $scriptFile.FullName
          Set-AzSynapseSqlScript -WorkspaceName $workspaceName -SqlPoolName $sqlPoolName -SqlDatabaseName $databaseName -DefinitionFile $scriptFilePath

          Write-Host "Uploaded script file: $scriptFilePath"
          }
          Write-Host "SUCCESS"
