name: Upload SQL to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/setup-azurerm@v1
        with:
          azpsVersion: '3.10.0'

      - name: Upload SQL files to Azure Synapse
        run: |
          $storageAccountName = "satyadldemo"
          $containerName = "satyadlfs"
          $localFolderPath = "/sqlfiles"
          $context = New-AzStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $env:AZURE_STORAGE_KEY

          Get-ChildItem -Path $localFolderPath -Filter "*.sql" -File -Recurse | ForEach-Object {
              $blobPath = $_.FullName.Replace($localFolderPath, "").TrimStart("/")
              $blobName = $_.Name
              Set-AzStorageBlobContent -Container $containerName -File $_.FullName -Blob "$blobPath/$blobName" -Context $context
          }
